### ISSUE TITLE
Code Louisville Python Checklist 

### ISSUE THREAD

**Issue by JagJones** [JagJones/Experimental_Coding#2]
🐍 🐍 🐍 
**Week One**
*1/14*
- [x] [Python Basics](https://teamtreehouse.com/library/python-basics-3)
- [x] [Setting up a Local Python Environment]() *I have questions here.*

**Week Two**
*1/21*
- [x] [Practice Input and Output in Python](https://teamtreehouse.com/library/practice-input-and-output-in-python)
- [x] [Intro to Lists](https://teamtreehouse.com/library/introducing-lists)
- [x] [Loops](https://teamtreehouse.com/library/practice-writing-loops-in-python)
- [x] [Comparisons](https://teamtreehouse.com/library/practice-comparisons-in-python)
- [x] [Practice Basic Math with Python](https://teamtreehouse.com/library/practice-basic-math-calculations-in-python)
- [x] [Jupyter Notebooks](https://teamtreehouse.com/library/jupyter-notebooks)

**Week Three**
*1/28*
- [x] [Practicing with Strings and Lists](https://teamtreehouse.com/library/practice-using-strings-and-lists-in-python)
- [x] [Creating and Indexing Lists](https://teamtreehouse.com/library/practice-creating-and-indexing-lists)
- [x] [Tuples](https://teamtreehouse.com/library/introducing-tuples)
- [x] [Functions, Packaging, and Unpacking](https://teamtreehouse.com/library/functions-packing-and-unpacking)
- [x] [Practice Creating and Using Functions in Python](https://teamtreehouse.com/library/practice-creating-and-using-functions-in-python)

**Week Four**
*2/4*
- [x] [Python Sequences](https://teamtreehouse.com/library/python-sequences)
- [x] [Intro to Dictionaries](https://teamtreehouse.com/library/introducing-dictionaries)
- [x] [Intro to Dunder Main](https://teamtreehouse.com/library/understanding-dunder-main-main)

**Week Five**
*2/11*
- [x] [Object-Oriented Python](https://teamtreehouse.com/library/objectoriented-python-2)

**Week Six**
*2/18*
- [x] [Write Better Python](https://teamtreehouse.com/library/write-better-python)
- [x] [Dates and Times in Python](https://teamtreehouse.com/library/dates-and-times-in-python)
- [x] [Regular Expression in Python](https://teamtreehouse.com/library/regular-expressions-in-python)

**Week Seven**
*2/25*
- [x] [Python File I/0](https://teamtreehouse.com/library/python-file-io)
- [x] [Python for File Systems](https://teamtreehouse.com/library/python-for-file-systems)
- [x] [CSV and JSON in Python](https://teamtreehouse.com/library/csv-and-json-in-python)

**Week Eight**
*3/4*
- [x] [Python Testing]()
- [x] [Python Comprehensions]()
- [x] [Python Decorators]()
- [x] [Python Type Hinting]()

**Week Nine**
*3/11*
- [x] [PyCharm]()
- [x] [Using Databases in Python]()

**Networking Events**
*x2*
- [x] []()
- [x] []()

🎉 **Projects Due** 🎉 
*Fri 4/2 by 12pm* 
- [ ] *Will add link when it's available.*
